# Generated by Django 2.2.6 on 2019-10-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0002_auto_20191006_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['id']},
        ),
    ]
