# Generated by Django 2.2.6 on 2019-10-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0003_auto_20191010_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
